# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 16:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmopolitan', '0004_postcode_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('type_id', models.CharField(max_length=200)),
                ('polygon', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
    ]
